### ISSUE TITLE
Translations of objects

### ISSUE THREAD

**Issue by Yaco** [ColdTrick/language_selector#10]
Hi!
I need a solution that allows to have translated version of certain contents (objects). For example: allow a user to create a blog entry (or group page, etc.) in English and Spanish (and maybe others), so the blog entry is accessible in those languages.

I understand the this plugin doesn't include this feature. Am I right?

If not, would it be possible to add it? Would you be interested in doing it? Maybe it require a sponsorship?

Hope I am clear. Thx!

**Comment by jdalsem** [comment]
> I understand the this plugin doesn't include this feature. Am I right?

you are right


> If not, would it be possible to add it?

This plugin will probably not be the place for it (as it is meant for the language files)


> Would you be interested in doing it? Maybe it require a sponsorship?

Could be interesting, but would probably require a lot of time building it. If you are willing to finance a couple of weeks work, please contact me at info@coldtrick.com
